### ISSUE TITLE
Can not build application

### ISSUE THREAD

**Issue by omarodev** [NlaakStudios/gowaf-templates#12]
When run 'go build' command in terminal , get the following message. 

# _/Users/toptal/go/src/github.com/NlaakStudios/gowaf-templates/Demo
./main.go:14:24: not enough arguments in call to app.NewMVC
	have ()
	want (string, ...string)
./main.go:38:20: undefined: controller.NewLanding
./main.go:51:9: not enough arguments in call to app.Run
	have ()
	want (app.RegisterFunc)

**Comment by NlaakStudios** [comment]
update the repo, that is a change made yesterday on the execution order.
run for gowaf-templates ... get the latest version
then update gowaf: ```go get -u github.com/NlaakStudios/gowaf

**Comment by omarodev** [comment]
After update, run go build command again.
But I still have errors.

# _/Users/toptal/gowaf-templates/Demo
./main.go:34:18: undefined: controller.NewLanding
./main.go:49:25: undefined: Version

**Comment by NlaakStudios** [comment]
hmmm, why is mine building .. looking into it. we should have exact same if you are synced. Give me a bit, have another meeting to go to.

**Comment by omarodev** [comment]
When run build command, I have this error. 
# _/Users/toptal/gowaf-templates/Demo
./main.go:34:18: undefined: controller.NewLanding

**Comment by NlaakStudios** [comment]
Working.
